// Generated by CoffeeScript 1.6.3
define(['backbone'], function(Backbone) {
  return Backbone.View.extend({
    el: 'body',
    load: function() {
      return this.render();
    },
    render: function() {
      this.$el.append('<div>yo!</div>');
      return this;
    }
  });
});
